export enum EMetadataType {
  HOME = 'HOME',
  SERVICE_LANDING = 'SERVICE_LANDING',
  SERVICE = 'SERVICE',
  PRODUCT_LANDING = 'PRODUCT_LANDING',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  CONTACT = 'CONTACT',
  ABOUT = 'ABOUT',
}
